name: 'Setup Configu CLI'
description: 'Install and configure Configu CLI'
author: 'Configu'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  version:
    description: 'The version of Configu CLI to install. A value of `stable`|`latest`|`lts` will install the latest version of Configu CLI. Defaults to `stable`.'
    default: 'stable'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Setup Configu CLI Unix'
      shell: bash
      if: runner.os != 'Windows'
      env:
        CONFIGU_VERSION: ${{ inputs.version }}
      run: |
        if [[ $(command -v configu) == "" ]]; then
          curl https://cli.configu.com/install.sh | sh
        else
          echo "Configu CLI is already installed. No operation was performed."
        fi
    - name: 'Setup Configu CLI Windows'
      shell: pwsh
      if: runner.os == 'Windows'
      env:
        CONFIGU_VERSION: ${{ inputs.version }}
      run: |
        echo $env:PATH
        # Get-ChildItem -Recurse "C:\Program Files\configu"
        iex (iwr -UseBasicParsing https://cli.configu.com/install.ps1)
        # Get-ChildItem -Recurse "C:\Program Files\configu"
        
        Test-Path -Path "C:\Program Files\configu\bin"
        echo $env:PATH
        echo "C:\Program Files\configu\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo $env:GITHUB_PATH

        configu version

        # Start-Process -FilePath powershell -Verb RunAs -ArgumentList '-NoProfile','-InputFormat None','-ExecutionPolicy Bypass','-Command ""iex (iwr -UseBasicParsing https://cli.configu.com/install.ps1)""'
        # if [[ $(command -v configu) == "" ]]; then
        # else
        #   echo "Configu CLI is already installed. No operation was performed."
        # fi